# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=root 
  - password=Amer@9952349976 
- name: mysql-db-url
  literals:
  - database=lernopus-dev
  - url=jdbc:mysql://lernopus-app-mysql:8085/lernopus-dev?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - lernopus-app-server.yaml
  - lernopus-app-client.yaml  
